### ISSUE TITLE
tko_mail_smtp_per_user for odoo v10 not set "From" field

### ISSUE THREAD

**Issue by rfpk-del** [thinkopensolutions/tkobr-addons#156]
* install moduel
* setup mail.catchall.domain, mail.catchall.alias, mail.bounce.alias, 
* setup Outgoing and Incoming servers for user 
* send mail to client
Odoo try to send mail from proper smtp server, but "from" field seems like" bounce+xx-res.partner-xx@catchall.domain"
smtp server set 553 Error (SMTPSenderRefused)

**Comment by cmsalmeida** [comment]
Hi, thank you for your feedback.
That is because you have defined the system paramenters "mail.bounce.alias" and "mail.catchall.domain"
As in code: https://github.com/thinkopensolutions/oca-ocb/blob/10.0/addons/mail/models/mail_mail.py#L238
Try to remove mail.bounce.alias, leave mail.catchall.domain. Some servers don't allow that from field.
Please let us know if it worked.
Best regards

**Comment by ghost** [comment]
Hi, did it work?
