### ISSUE TITLE
tko_web_sessions_management

### ISSUE THREAD

**Issue by yelizariev** [thinkopensolutions/tkobr-addons#4]
Hi,
I'd like to report, that I've updated tko_web_sessions_management. Now it's possible to close any active session.
I've decided to move module to my repo and delete prefix from name:
https://github.com/yelizariev/addons-yelizariev/tree/8.0/web_sessions_management

**Comment by cmsalmeida** [comment]
Hi Ivan,
It's great to know that.
We where finishing some developments and bugs, and will add that module to our production apps repository very soon. By the way, it is an old version, please check new one in production, just pushed.
But why you move it? The best way to work together is having it in only one repository, I've added you to the team, so we can colaborate on that and other modules. Can you push those changes in our repository, we pushed latest version?

**Comment by yelizariev** [comment]
Hi Carlos,
I am not sure, that moving (and renaming) is a good idea, but I found this module in a poor quality with no updates for long time. Also, it's hard to organize my work with a lot of repositories, each of which I am interested only in one module. It's ok to do fork and propose small PR to fix something in some repository. But for module, where I think there should be done a lot of refactoring and updates, I could decide to move module to my repo.
I could change my mind in the future, though.

Feel free to take my updates and commit it (yourself) to your repository and continue work.

**Comment by cmsalmeida** [comment]
Hi,

You can find that the module pushed 2 days ago to our repository, has significant enhancements and bug fixes, because it was in development, like I said. We have others modules in development to be release soon to community.

Keeping the module in two different repositories will not help the end user to have latest developments and bug fixes, because neither you or we will update both codes. Nor the developers will know wich one they will use to add enhancements or bug fixes.

I think also that this is your decision, as long you keep the authoring like you did, but not good in terms of colaboration, future development and support. You should agree with me, that this kind of issues, don't incentivate us to publish modules like this one, in wich we are working at the moment, and can be a good contribution to Odoo community.

Any way thanks for your message, and contribution to the module!!
You can contact us at any time you wish.

Regards
